apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: research-assistant
  namespace: research-assistant
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: research-assistant.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: research-assistant
                port:
                  number: 8000
