apiVersion: v1
kind: Namespace
metadata:
  name: research-assistant
  labels:
    enviroment: production
    team: AI-Engineers
  annotations:
    description: "Namespace for the AI Research Assistant project workloads"
    owner: "abdelrhmanebied170@gmail.com"
